apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .OperatorName }}-admission-server
  namespace: {{ .Namespace }}
  labels:
    app: admission-webhook
    openebs.io/component-name: admission-webhook
    openebs.io/version: {{ .Params.APP_VERSION }}
spec:
  replicas: 1
  strategy:
    type: "Recreate"
    rollingUpdate: null
  selector:
    matchLabels:
      app: admission-webhook
  template:
    metadata:
      labels:
        app: admission-webhook
        name: admission-webhook
        openebs.io/version: {{ .Params.APP_VERSION }}
        openebs.io/component-name: admission-webhook
    spec:
      serviceAccountName: {{ .OperatorName }}-maya-operator
      containers:
        - name: admission-webhook
          image: quay.io/openebs/admission-server:{{ .Params.APP_VERSION }}
          imagePullPolicy: {{ .Params.IMAGE_PULLPOLICY }}
          args:
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=8
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: admission-server-certs
