{{- if .Params.SNAPSHOTOPERATOR.ENABLED }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .OperatorName }}-snapshot-operator
  namespace: {{ .Namespace }}
  labels:
    app: {{ .OperatorName }}
    component: snapshot-operator
    openebs.io/component-name: openebs-snapshot-operator
    openebs.io/version: {{ .Params.APP_VERSION }}
spec:
  selector:
    matchLabels:
      app: {{ .OperatorName }}
      name: openebs-snapshot-operator
      openebs.io/component-name: openebs-snapshot-operator
  replicas: {{ .Params.SNAPSHOTOPERATOR_REPLICAS }}
  strategy:
    type: "Recreate"
    rollingUpdate: null
  template:
    metadata:
      labels:
        app: {{ .OperatorName }}
        component: snapshot-operator
        name: openebs-snapshot-operator
        openebs.io/component-name: openebs-snapshot-operator
        openebs.io/version: {{ .Params.APP_VERSION }}
    spec:
      serviceAccountName: {{ .OperatorName }}-maya-operator
      containers:
      - name: {{ .OperatorName }}-snapshot-controller
        image: quay.io/openebs/snapshot-controller:{{ .Params.APP_VERSION }}
        imagePullPolicy: {{ .Params.IMAGE_PULLPOLICY }}
        env:
        - name: OPENEBS_NAMESPACE
          value: "{{ .Namespace }}"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        livenessProbe:
          exec:
            command:
            - pgrep
            - ".*controller"
          initialDelaySeconds: {{ .Params.SNAPSHOTOPERATOR_HC_DELAY }}
          periodSeconds: {{ .Params.SNAPSHOTOPERATOR_HC_PERIOD }}
        # OPENEBS_MAYA_SERVICE_NAME provides the maya-apiserver K8s service name,
        # that snapshot controller should forward the volume snapshot requests.
        # If not present, "maya-apiserver-service" will be used for lookup.
        # This is supported for openebs snapshot controller version 0.6-RC1 onwards
        - name: OPENEBS_MAYA_SERVICE_NAME
          value: "{{ .OperatorName }}-apiservice"
      - name: {{ .OperatorName }}-snapshot-provisioner
        image: quay.io/openebs/snapshot-provisioner:{{ .Params.APP_VERSION }}
        imagePullPolicy: {{ .Params.IMAGE_PULLPOLICY }}
        env:
        - name: OPENEBS_NAMESPACE
          value: "{{ .Namespace }}"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        # that snapshot provisioner should forward the volume snapshot PV requests.
        # This is supported for openebs snapshot provisioner version 0.6-RC1 onwards
        - name: OPENEBS_MAYA_SERVICE_NAME
          value: "{{ .OperatorName }}-apiservice"
        livenessProbe:
          exec:
            command:
            - pgrep
            - ".*provisioner"
          initialDelaySeconds: {{ .Params.SNAPSHOTOPERATOR_HC_DELAY }}
          periodSeconds: {{ .Params.SNAPSHOTOPERATOR_HC_PERIOD }}
{{- if .Params.SNAPSHOTOPERATOR_NODE_SELECTOR }}
      nodeSelector:
{{ toYaml .Params.SNAPSHOTOPERATOR_NODE_SELECTOR | indent 8 }}
{{- end }}
{{- if .Params.SNAPSHOTOPERATOR_TOLERATIONS }}
      tolerations:
{{ toYaml .Params.SNAPSHOTOPERATOR_TOLERATIONS | indent 8 }}
{{- end }}
{{- if .Params.SNAPSHOTOPERATOR_AFFINITY }}
      affinity:
{{ toYaml .Params.SNAPSHOTOPERATOR_AFFINITY | indent 8 }}
{{- end }}
{{- end }}
