{{- if .Params.NDM_OPERATOR_ENABLED }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .OperatorName }}-ndm-operator
  namespace: {{ .Namespace }}
  labels:
    app: {{ .OperatorName }}
    component: ndm-operator
    openebs.io/component-name: ndm-operator
    openebs.io/version: {{ .Params.APP_VERSION }}
    name: ndm-operator
spec:
  replicas: {{ .Params.NDM_OPERATOR_REPLICAS }}
  strategy:
    type: "Recreate"
    rollingUpdate: null
  selector:
    matchLabels:
      app: {{ .OperatorName }}
      name: openebs-ndm-operator
      openebs.io/component-name: ndm-operator
  template:
    metadata:
      labels:
        app: {{ .OperatorName }}
        component: ndm-operator
        name: ndm-operator
        openebs.io/component-name: ndm-operator
        openebs.io/version: {{ .Params.APP_VERSION }}
    spec:
      serviceAccountName: {{ .OperatorName }}-maya-operator
      containers:
      - name: {{ .OperatorName }}-ndm-operator
        image: quay.io/openebs/node-disk-operator-amd64:{{ .Params.NDM_VERSION }}
        imagePullPolicy: {{ .Params.IMAGE_PULLPOLICY }}
        readinessProbe:
          exec:
            command:
            - stat
            - /tmp/operator-sdk-ready
          initialDelaySeconds: {{ .Params.NDM_OPERATOR_READINESS_DELAY }}
          periodSeconds: {{ .Params.NDM_OPERATOR_READINESS_PERIOD }}
          failureThreshold: {{ .Params.NDM_OPERATOR_FAILURE_THRESHOLD }}
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
            # the service account of the ndm-operator pod
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
        - name: OPERATOR_NAME
          value: "node-disk-operator"
        - name: CLEANUP_JOB_IMAGE
          value: quay.io/openebs/linux-utils:{{ .Params.NDM_OPERATOR_CI_VERSION }}
{{- if .Params.NDM_OPERATOR_NODE_SELECTOR }}
      nodeSelector:
{{ toYaml .Params.NDM_OPERATOR_NODE_SELECTOR | indent 8 }}
{{- end }}
{{- if .Params.NDM_OPERATOR_TOLERATIONS }}
      tolerations:
{{ toYaml .Params.NDM_OPERATOR_TOLERATIONS | indent 8 }}
{{- end }}
{{- end }}
