{{- if .Params.LOCALPV_ENABLED }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .OperatorName }}-localpv-provisioner
  namespace: {{ .Namespace }}
  labels:
    app: {{ .OperatorName }}
    name: {{ .OperatorName }}-localpv-provisioner
    component: localpv-provisioner
    openebs.io/component-name: openebs-localpv-provisioner
    openebs.io/version: {{ .Params.APP_VERSION }}
spec:
  selector:
    matchLabels:
      app: {{ .OperatorName }}
  replicas: {{ .Params.LOCALPV.REPLICAS }}
  strategy:
    type: "Recreate"
    rollingUpdate: null
  template:
    metadata:
      labels:
        app: {{ .OperatorName }}
        component: localpv-provisioner
        name: openebs-localpv-provisioner
        openebs.io/component-name: openebs-localpv-provisioner
        openebs.io/version: {{ .Params.APP_VERSION }}
    spec:
      serviceAccountName: {{ .OperatorName }}-maya-operator
      containers:
      - name: {{ .OperatorName }}-localpv-provisioner
        image: quay.io/openebs/provisioner-localpv:{{ .Params.APP_VERSION }}
        imagePullPolicy: {{ .Params.IMAGE_PULLPOLICY }}
        env:
        # OPENEBS_IO_K8S_MASTER enables openebs provisioner to connect to K8s
        # based on this address. This is ignored if empty.
        # This is supported for openebs provisioner version 0.5.2 onwards
        #- name: OPENEBS_IO_K8S_MASTER
        #  value: "http://10.128.0.12:8080"
        # OPENEBS_IO_KUBE_CONFIG enables openebs provisioner to connect to K8s
        # based on this config. This is ignored if empty.
        # This is supported for openebs provisioner version 0.5.2 onwards
        #- name: OPENEBS_IO_KUBE_CONFIG
        #  value: "/home/ubuntu/.kube/config"
        # OPENEBS_NAMESPACE is the namespace that this provisioner will
        # lookup to find maya api service
        - name: OPENEBS_NAMESPACE
          value: "{{ .Namespace }}"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        # OPENEBS_IO_BASE_PATH is the environment variable that provides the
        # default base path on the node where host-path PVs will be provisioned.
        - name: OPENEBS_IO_ENABLE_ANALYTICS
          value: "{{ .Params.ANALYTICS_ENABLED }}"
        - name: OPENEBS_IO_BASE_PATH
          value: "{{ .Params.LOCALPV_BASEPATH_DIR }}"
        - name: OPENEBS_IO_HELPER_IMAGE
          value: quay.io/openebs/openebs-tools:{{ .Params.LOCALPV_HELPER_IMAGE_VERSION }}
        - name: OPENEBS_IO_INSTALLER_TYPE
          value: "kudo-operator"
        livenessProbe:
          exec:
            command:
            - pgrep
            - ".*localpv"
          initialDelaySeconds: {{ .Params.LOCALPV_HC_DELAY }}
          periodSeconds: {{ .Params.LOCALPV_HC_PERIOD }}
{{- if .Params.LOCALPV_NODE_SELECTOR }}
      nodeSelector:
{{ toYaml .Params.LOCALPV_NODE_SELECTOR | indent 8 }}
{{- end }}
{{- if .Params.LOCALPV_NODE_TOLERATIONS }}
      tolerations:
{{ toYaml .Params.LOCALPV_NODE_TOLERATIONS | indent 8 }}
{{- end }}
{{- if .Params.LOCALPV_NODE_AFFINITY }}
      affinity:
{{ toYaml .Params.LOCALPV_NODE_AFFINITY | indent 8 }}
{{- end }}
{{- end }}
