{{ if eq .Params.RBAC_ENABLED "true" }}
apiVersion: v1
kind: Service
  name: maya-apiserver
  labels:
    app: {{ .OperatorName }}
    component: apiserver
    name: maya-apiserver
    openebs.io/component-name: maya-apiserver
    openebs.io/version: {{ .Params.APP_VERSION }}
metadata:
  name: maya-apiserver-service
  namespace: {{ .Namespace }}
  labels:
    app: {{ .OperatorName }}
    component: apiserver
    name: maya-apiserver-service
    openebs.io/component-name: maya-apiserver-svc
    openebs.io/version: {{ .Params.APP_VERSION }}
spec:
  ports:
  - name: api
    port: {{ .Params.APISERVER_PORT_EXT }}
    targetPort: {{ .Params.APISERVER_PORT_INT }}
    protocol: TCP
  selector:
    app: {{ .OperatorName }}
    component: apiserver
  sessionAffinity: None
{{- end }}
