apiVersion: v1
kind: Service
metadata:
  name: admission-server-svc
  namespace: {{ .Namespace }}
  labels:
    app: admission-webhook
    openebs.io/component-name: admission-webhook-svc
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: admission-webhook
